name: Deploy to cPanel FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📦 Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: 📂 Sync files via LFTP
        run: |
          lftp -e "set ssl:verify-certificate false; set ftp:ssl-allow true; set ftp:passive-mode true; set net:timeout 15; set net:max-retries 2; mirror -R -v --only-newer -X '.git*' -X '.github*' ./ public_html/; quit" -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_SERVER }}"
